---
- name: update system
  hosts: all
  become: true
  
  tasks:
  - name: update
    apt:
      update_cache: yes
  
  - name: install soft
    apt:
      pkg:
      - docker.io
      state: present